import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const APP = path.resolve(process.argv[2]);
const srv = http.createServer((q, r) => { const f = path.join(APP, q.url.split('?')[0] === '/' ? 'index.html' : q.url.split('?')[0]); fs.readFile(f, (e, d) => { if (e) { r.writeHead(404); r.end(); } else { r.writeHead(200, { 'Content-Type': f.endsWith('.html') ? 'text/html' : f.endsWith('.json') ? 'application/json' : 'application/octet-stream' }); r.end(d); } }); }).listen(8080);
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, serviceWorkers: 'block' });
await ctx.addInitScript(() => { if (!sessionStorage.getItem('s')) { sessionStorage.setItem('s', 1); localStorage.setItem('canvass-log.view', JSON.stringify({ lat: 43.7068, lng: -116.6201, z: 12 })); localStorage.setItem('canvass-log.eventfilters', JSON.stringify({ from: 'map', radius: '0' })); localStorage.setItem('canvass-log.tab', 'events'); } });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:8080/'); await page.waitForTimeout(3000);
const n = await page.evaluate(() => JSON.parse(localStorage.getItem('canvass-log.eventfeed')).events.length);
await page.waitForFunction(n => { const s = JSON.parse(localStorage.getItem('canvass-log.eventstate') || '{}'); return Object.values(s).filter(x => x.geo).length >= n; }, n, { timeout: 150000, polling: 2000 }).catch(() => console.log('geocode timed out'));
const geo = await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('canvass-log.eventstate') || '{}'); return Object.fromEntries(Object.entries(s).filter(([, v]) => v.geo).map(([k, v]) => [k, v.geo])); });
console.log('GEO ' + JSON.stringify(geo));
await page.waitForTimeout(8000);
const rows = await page.$$eval('#evRows .erow', r => r.map(x => x.innerText.replace(/\s+/g, ' ').trim().slice(0, 170)));
console.log('source:', await page.textContent('#evSource'));
console.log('rows:', rows.length, '\n  ' + rows.join('\n  '));
await page.screenshot({ path: 'events.png' });
await page.click('#evRows .erow'); await page.waitForTimeout(3000);
console.log('first sheet:', (await page.textContent('#evBody')).replace(/\s+/g, ' ').slice(0, 1500));
console.log('badge:', await page.textContent('#inboxCount'), 'errors:', errs);
await browser.close(); srv.close();
